/**
 * REDUX ACTION TYPES CONSTANTS
 */
export const GRID_INIT = 'GRID_INIT';

export const CELL_MARK = 'CELL_MARK';

export const CELL_MARK_START = 'CELL_MARK_START';
export const CELL_MARK_TARGET = 'CELL_MARK_TARGET';
export const CELL_MARK_WORM_ENTER = 'CELL_MARK_WORM_ENTER';
export const CELL_MARK_WORM_EXIT = 'CELL_MARK_WORM_EXIT';

export const PATH_BUILD = 'PATH_BUILD';

export const ELEMENT_PICK = 'ELEMENT_PICK';
